### ISSUE TITLE
How to perform sequential inference instead of whole video process?

### ISSUE THREAD

**Issue by jiangzhengkai** [sukjunhwang/IFC#8]
Thanks for your great work. I want to know how to perform sequential inference instead of the whole video process.

**Comment by sukjunhwang** [comment]
Hi @jiangzhengkai,

cfg.INPUT.SAMPLING_FRAME_NUM is what controls the input clip length.
As the parameter is set to 5 by default, it would run in a sequential inference mode unless modified.
