### ISSUE TITLE
No "Annotations" found in the dataset

### ISSUE THREAD

**Issue by HarryHsing** [sukjunhwang/IFC#9]
Hi, I try to do the evaluation, but I do not have Annotations files in the dataset I downloaded. May you give me some clue?

**Comment by sukjunhwang** [comment]
Hi @HarryHsing ,

the annotations of YouTube-VIS dataset is not publicly available, so you should go to the evaluation server and upload the compressed result json file.
Here is the link: https://competitions.codalab.org/competitions/20128
